apiVersion: ENC[AES256_GCM,data:kac=,iv:cKuGCRFdw0zH//+wy27XQZ0zu0ov+BWofga8SGJxaQQ=,tag:ddGOllLXWfV2/24XPjSxyw==,type:str]
kind: ENC[AES256_GCM,data:HiDM5MNx,iv:m7S6D1ZieNDjuXp+BOlTOMmQ3kLYVFKMRsfs20pxHZI=,tag:4L/ymliPlIYX9xU8OVF3SQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kkziYtBbTXtBMNC5hH99,iv:6Vr9a0520MCHEOP3LKeErTP+O3Vk/BTWDHHY4fGHjUM=,tag:7WKncSWotSUZOJu7UNOtCw==,type:str]
    namespace: ENC[AES256_GCM,data:ZQQ1YToSWDPXog==,iv:Waqo5X/7gUmMZVghw6GRKjTG8UMBMOtjTf/wK52c/fg=,tag:JNE4yKf04i9EDnhdH82D8g==,type:str]
type: ENC[AES256_GCM,data:IOrBLZ+w,iv:iXyWkI6T94VBOK6KU5eQGLVc0lDD/+b4Jsrn9Pkvd98=,tag:dUeKMHWujOcR/4R2Y6qkjA==,type:str]
data:
    client-id: ENC[AES256_GCM,data:06kZ1XU+9AytevPiwDficyyq9rYfusbxOPHddA==,iv:4zXQCm7hDZco8P15If4UwbkzkJrdPtH23yPfJD4jo0w=,tag:IrGGe9WevfLGmPF05oyEQw==,type:str]
    client-secret: ENC[AES256_GCM,data:+NmAmwSComqps1lKT8/darBMXXevPz20v1vMKEyDjECASqXrcDW4QoRJ3puaiMsEw6xxHc1xwco=,iv:Im/LeXLWLnfouohR+vl523b0TUuT5q59c6pUhsF90tI=,tag:a/d7tCBULFlI/sTMP69fAw==,type:str]
    issuer-uri: ENC[AES256_GCM,data:UcFzuaJAT0qKWF3L/PXazsLtG8nyG9tKt/NNblhWHMxeLUvj+rHEl8EPduXJuFX+CjbfBnweSNgnESH3J9slNPtuoS6ImiwCVAaXhg==,iv:sVl9XkkirdXHz2wrPnQ+nfIrZxMlqCBsu+YhLQOEzZc=,tag:Gu0LNF//KjxyoyvyEXDidg==,type:str]
    scope: ENC[AES256_GCM,data:dVu3tcCpnN4kWbxERQep5nIAwVxhLPRhLy0xNHWCABbGCDRza1tsZOqwRQ0=,iv:I/T9lFUjPhfiVfVGNiHz0FgFGedYgxVT5ZVMCnIhM3A=,tag:WcxF1q2YYmz9JfOpp4t0aA==,type:str]
    user-name-attribute: ENC[AES256_GCM,data:SMzVj0JB96LzmPFT,iv:K97aOr9vq88teKp9sJj9JCIYJijhrM+qHtFI1bhnYfQ=,tag:fcG8lufACBvqVsQTPJT03g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSUI0VHMyT2EyNVBSWVVY
            eUZEcnRXMHQ3cXBWV0hRam9DT2dyWmxWc2pJCjdQZExVZzA1eEREdnhHK3hqNURk
            NkZMNllmT1JnY0t6aHU3VnUvcG5HY0EKLS0tIFFxS0hVbE9RQWpVRHRlR2ZCbUpo
            K2VRQlVhQ3NoMHJGYzB1S0trUm4xMWcK62aZm1/NNf6jFSR51Bfdag45eqVdWqbp
            D6ofbzpRVE4/mQlvprgxML6AQVjNmUiQ2ntDqd4B/80M/B0PFOwTCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T16:47:06Z"
    mac: ENC[AES256_GCM,data:EpTmtwb+H7shnv87pj0c8er7e1+WgIRhHR+K+TnsJtU+xZrnnsiVheNWm/KyzKJ7RmpjKXvUuZ/7aJJ74PpG2jEyZxoH8Z0qLKEEstBMKCd5l4LLtdreNxQrJEgKbqSF0MPBJBoxR+0OWoaZjICkkeg6mWe+X1TF6mmbN96sQjo=,iv:s3L3YbI6xaQyzFFv1mJjgVzrFFLXXU1l6gdQa7WXeBU=,tag:gSskyynamI1WRjQIWDHI7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
